
  - block:
 
    - name: DEBUG -                 üü¢ API URL
      debug: 
        var: k8s_apiurl


    - name: DEBUG -                 üü¢ API KEY
      debug: 
        var: k8s_apikey

    - name: OCP Login
      shell: |
        oc login --token={{ my_k8s_apikey }} --server={{ my_k8s_apiurl }} --insecure-skip-tls-verify
      ignore_errors: true
      register: EXEC_RESULT
    - name: üü£  OUTPUT
      debug: 
        var: EXEC_RESULT.stdout_lines
        #verbosity: 1





    - name: Reset Fiber Uplink
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo " üöÄ Reset Fiber Uplink"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo ""
        echo ""



        echo "   ----------------------------------------------------------------------------------------------------------"
        echo "    üõ†Ô∏è Initialize"
        echo "   ----------------------------------------------------------------------------------------------------------"
        export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
        export TOPO_REST_USR=$(oc get secret aiops-topology-asm-credentials -n $AIOPS_NAMESPACE -o jsonpath='{.data.username}' | base64 --decode)
        export TOPO_REST_PWD=$(oc get secret aiops-topology-asm-credentials -n $AIOPS_NAMESPACE -o jsonpath='{.data.password}' | base64 --decode)
        export TOPO_MGT_ROUTE="https://"$(oc get route -n $AIOPS_NAMESPACE aiops-topology-topology -o jsonpath={.spec.host})
        export LOGIN="$TOPO_REST_USR:$TOPO_REST_PWD"



        echo ""
        echo "   ----------------------------------------------------------------------------------------------------------"
        echo "    ‚ôªÔ∏è Reset Fiber Uplink between Bern (CH) and Frankfurt (DE)"
        echo "   ----------------------------------------------------------------------------------------------------------"

        echo "    URL: $TOPO_MGT_ROUTE/1.0/rest-observer/rest/resources"
        echo "    LOGIN: $LOGIN"

        export OBJ_ID=$(curl -k -s -X "GET" "$TOPO_MGT_ROUTE/1.0/topology/resources?_filter=name%3Dfrapod01&_filter=entityTypes%3DfiberConnection&_field=uniqueId&_include_global_resources=false&_include_count=false&_include_status=false&_include_status_severity=false&_include_metadata=false&_return_composites=false" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255'|jq -r -c '._items[]|._id'| tail -1)
        echo $OBJ_ID
        echo "    OBJ_ID: $OBJ_ID"

        export result=$(curl -k -s -X "POST" "$TOPO_MGT_ROUTE/1.0/topology/resources/$OBJ_ID" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d '{"availability": "OK"}')
        echo "    result: $result"


        export OBJ_ID=$(curl -k -s -X "GET" "$TOPO_MGT_ROUTE/1.0/topology/resources?_filter=name%3Dbepod01&_filter=entityTypes%3DfiberConnection&_field=uniqueId&_include_global_resources=false&_include_count=false&_include_status=false&_include_status_severity=false&_include_metadata=false&_return_composites=false" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255'|jq -r -c '._items[]|._id'| tail -1)
        echo $OBJ_ID
        echo "    OBJ_ID: $OBJ_ID"

        export result=$(curl -k -s -X "POST" "$TOPO_MGT_ROUTE/1.0/topology/resources/$OBJ_ID" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d '{"availability": "OK"}')
        echo "    result: $result"




        echo ""
        echo "   ----------------------------------------------------------------------------------------------------------"
        echo "    üì• Restore Ratings Service"
        echo "   ----------------------------------------------------------------------------------------------------------"
        oc patch service mysql -n robot-shop --patch '{"spec": {"selector": {"service": "mysql"}}}'
        oc set env deployment ratings -n robot-shop PDO_URL-
        oc set env deployment load -n robot-shop ERROR=0
        oc delete pod $(oc get po -n robot-shop|grep shipping|awk '{print$1}') -n robot-shop --ignore-not-found
    
        export MYSQL_ID=$(curl -X "GET" "$TOPO_MGT_ROUTE/1.0/topology/resources?_filter=name%3Dmysql&_filter=entityTypes%3Ddeployment&_field=uniqueId&_include_global_resources=false&_include_count=false&_include_status=false&_include_status_severity=false&_include_metadata=false&_return_composites=false" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255'|jq -r -c '._items[]|._id'| tail -1)
        echo $MYSQL_ID
    
        export result=$(curl -X "POST" "$TOPO_MGT_ROUTE/1.0/topology/resources/$MYSQL_ID" --insecure -u $LOGIN -H 'Content-Type: application/json' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d '{"innodb_buffer_pool_size": "8GB"}')
        echo $result



        echo ""
        echo ""
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo " ‚úÖ Reset Fiber Uplink - DONE"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"

      ignore_errors: true
      register: EXEC_RESULT
    - name: üü£  OUTPUT
      debug: 
        var: EXEC_RESULT.stdout_lines
        #verbosity: 1




