
  - block:
 
    - name: DEBUG -                 ðŸŸ¢ API URL
      debug: 
        var: k8s_apiurl


    - name: DEBUG -                 ðŸŸ¢ API KEY
      debug: 
        var: k8s_apikey



    - name: Scale ratings deployment to 1
      kubernetes.core.k8s_scale:
        host: "{{k8s_apiurl}}"
        api_key: "{{k8s_apikey}}"
        api_version: v1
        kind: Deployment
        name: ratings
        namespace: robot-shop
        replicas: 1
        wait_timeout: 60